- hosts: common

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: true
    
    - name: install cow thing
      ansible.builtin.apt:
        name: cowsay
        state: latest
      become: true  

    - name: shell cow
      ansible.builtin.shell: cowsay "Hello world!"
      register: cowsay_result

    - name: create www dir
      file:
        path: /var/tmp/www/
        owner: yarik
        state: directory

    - name: copy index.html
      ansible.builtin.template:
        src: ./templates/index.html.j2
        dest: "{{ root_dir  }}/index.html"
        owner: yarik
        mode: '0755'
      become: true

    - name: copy nginx conf
      ansible.builtin.template:
        src: ./templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: yarik
        mode: '0755'
      become: true
      notify:
        - restart nginx

  handlers: 
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true  



      
