- hosts: common
  vars:
    nginx_port: 80
    root_dir: /var/tmp/www
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: true
    
    - name: create www dir
      file:
        path: /var/tmp/www/
        owner: yarik
        state: directory

    - name: copy index.html
      ansible.builtin.copy:
        src: ./files/index.html
        dest: "{{ root_dir  }}/index.html"
        owner: yarik
        mode: '0755'
      become: true

    - name: copy nginx conf
      ansible.builtin.template:
        src: ./templates/nginx.conf.j2
        dest: "{{ root_dir }}/nginx.conf"
        owner: yarik
        mode: '0755'
      become: true
      notify:
        - restart nginx

  handlers: 
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true  



      
